# 백터, 행렬, 배열

## 1.1벡터 만들기

목표: 넘파이로 1차원 배열 생성

In [1]:
import numpy as np
vector_row = np.array([1,2,3]) #행이 하나
vector_column = np.array([[1],
                         [2],
                         [3]]) #열이 하나

> * 넘파이의 핵심 데이터 구조는 다차원배열   
> * 벡터는 1차원 배열로 생성   
> * 배열은 행(수평) 또는 열(수직)으로 만들 수 있다.

***

> * 넘파이 배열은 ndarray 클래스의 객체이다.

In [2]:
print(type(vector_row))

<class 'numpy.ndarray'>


> > ### ndarray 클래스   
> > 첫번째 매개변수에 배열의 크기를 정수 튜플로 지정해 배열 생성 가능   
BUT 권장하지 않음

In [20]:
bad_way = np.ndarray((3,))  
print(bad_way)

[ 1.14207443e-311  0.00000000e+000 -4.94065646e-324]


In [21]:
bad_way2 = np.ndarray((3,4)) #3=행, 4=열
print(bad_way2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


> > ### asarray 함수   
함수입력이 넘파이 배열일 경우 새로운 배열 생성 안함

In [106]:
a=[1,2,3]
new_row=np.asarray(a)

print(id(a))
print(id(new_row))

b=np.ndarray((3,))
new_row2=np.asarray(b)

print(id(b))
print(id(new_row2))
print(type(new_row2))

2559576377416
2559576389952
2559576364016
2559576364016
<class 'numpy.ndarray'>


In [27]:
new_row=np.asarray(vector_row)
new_row is vector_row #원본과 동일, 새로운 배열 생성x

True

> > ### array 함수   
입력 배열을 복사할지 선택하는 copy 매개변수 존재   
copy 매개변수의 기본값은 True -> 배열의 복사본 생성

In [28]:
new_row1 = np.array(vector_row)
new_row1 is vector_row #새로운 배열 생성

False

> > #### copy 메소드   
배열 복사의 의도를 정확히 밝히는 용도

In [29]:
new_row = vector_row.copy()
new_row is vector_row

False

***

## 1.2 행렬만들기   

목표: 넘파이로 2차원 배열 만들기

In [52]:
import numpy as np
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]]) #
matrix_object = np.mat([[1,2],
                       [1,2],
                       [1,2]]) #
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [53]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

위의 행렬데이터 구조(matrix_object)는 2가지 이유로 권장하지 않는다.   
1. 배열이 넘파이 표준 데이터 구조다
2. 대부분 넘파이 함수는 배열을 반환하고 행렬 객체는 반환하지 않기 때문



> ### empty 함수   
초깃값 대신 크기만 지정해 임의의 값이 채워진 배열을 만든다.

In [98]:
empty_matrix = np.empty((3,2))
empty_matrix

array([[-0.47113526,  1.26271548],
       [-1.17051545,  1.0657892 ],
       [-0.69993739,  0.14407911]])

> ### zeros 함수, ones 함수
zeros : 0으로 채운 배열을 만든다.   
ones : 1로 채운 배열을 만든다.

In [44]:
zero_matrix=np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
one_matrix=np.ones((3,2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

> ### full 함수   
특정값으로 채운 배열 생성   
첫번째 매개변수에는 배열의 크기, 두번째 매개변수에는 채울 값을 전달

In [99]:
seven_matrix = np.zeros((3,2)) + 7
seven_matrix

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [100]:
seven_matrix = np.full((3,2), 7)
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

***

## 1.3 희소 행렬 만들기   

목적: 데이터에 0이 아닌 값이 매우 적을때!, 효율적으로 표현하기

In [101]:
import numpy as np
from scipy import sparse

matrix=np.array([[0,0],
                [0,1],
                [3,0]])

matrix_sparse= sparse.csr_matrix(matrix) #sparse.csr_matrix(배열) : CSR행렬 생성
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


**희소행렬은 0이 아닌 원소만 저장, 다른 모든 원소는 0이라 가정**   

> ### Comprassed Sparse Row(CSR) 행렬   
* ```(m, n) a : m+1번째 행의 n+1번째 열에 있는 원소가 a```   
* 0인 원소를 아무리 많이 추가해도 희소행렬의 크기는 바뀌지 않는다   
* 이 외 행렬 : 리스트의 리스트, 키의 딕셔너리




In [136]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,1,0,0,0,0,0,0,0,0],
                        [3,0,0,0,0,0,0,0,0,0]])  #밀집배열 생성
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


### 역으로 생성하기...sparse_matrix에서 Dense_matrix로   

* 밀집배열 생성 : 원소의 행과 열의 인덱스를 직접 지정해 희소행렬 생성
   1. 희소행렬에 (data, (row_index(행), col_index(열)))로 구성된 튜플 전달
   2. shape 매개변수에서 0을 포함한 희소행렬의 전체 크기 지정
   3. toarray메서드 or todense 메서드를 사용해 변환

In [137]:
matrix_sparse_2 = sparse.csr_matrix(([1,3], ([1,2], [1,0])), shape=(3, 10))

print(matrix_sparse_2)
print(matrix_sparse_2.toarray())  #밀집배열로 변환
print(matrix_sparse_2.todense())  #np.matrix 객체 반환

  (1, 1)	1
  (2, 0)	3
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


***   

## 1.4원소 선택하기

In [108]:
import numpy as np
vector = np.array([1,2,3,4,5,6]) #행벡터 생성
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [109]:
vector[2]

3

In [110]:
matrix[1,1]

5

> * 넘파이 배열의 인덱스는 0부터 시작

In [111]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [112]:
vector[:3] #3번째 포함 그 이전의 모든 원소

array([1, 2, 3])

In [113]:
vector[3:] #3번째 이후 모든 원소

array([4, 5, 6])

In [74]:
vector[-1] #마지막 원소

6

In [114]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

> ### 팬시인덱싱   
* 행과 열의 인덱스 리스트를 전달해 배열의 원소 선택
* (기능)

In [140]:
matrix[[0,2]] #첫번째, 세번째 행 선택

array([[1, 2, 3],
       [7, 8, 9]])

In [118]:
matrix[[0,2],[1,0]] # [row_index, col_index] -> (0,1), (2,0) 위치의 원소 선택

array([2, 7])

In [117]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

> * 불리언 마스크 배열의 경우

In [120]:
mask = matrix > 5
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [121]:
matrix[mask]  #블리언 마스크 배열을 사용해 원소 선택

array([6, 7, 8, 9])

***   

## 1.5행렬정보 확인하기   

목적 : 행렬크기, 원소 개수, 차원 구하기

In [141]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

matrix.shape  #행렬크기 확인

(3, 4)

In [86]:
matrix.size #행렬의 원소 갯수 확인

12

In [87]:
matrix.ndim #차원수 확인

2

In [88]:
matrix.dtype #원소의 데이터 타입 확인

dtype('int32')

In [89]:
matrix.itemsize #원소 하나가 차지하는 바이트 크기

4

In [91]:
matrix.nbytes #배열 전체가 차지하는 바이트 크기 items x size

48

***   

## 1.6벡터화 연산 적용하기   


In [142]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

add_100 = lambda i: i+100 
#함수 adder는 인수 i를 받아들이고 이를 취하는 함수, 람다를 반환한다.


> ### lambda 함수
```
lambda argument : 표현식
```   
* 프로그래밍에서 익명의 함수를 참조   
* 이름없이 빠르게 함수를 임의로 사용,제거 가능   

> ### vectorize 클래스   
* 배열의 일부나 전체에 적용하도록 함수를 변환   
* 기본적으로 원소를 순회하는 for루프를 구현한 것으로 성능향상은 되지않음


In [143]:
vectorized_add_100 = np.vectorize(add_100) # 벡터화된 함수 생성
vectorized_add_100(matrix) #행렬의 모든 원소에 함수를 적용한다

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])


### broadcasting

* 차원이 달라도 넘파이 배열 간 연산 수행이 가능함   
* 배열에 차원을 추가하거나 반복해서 배열의 크기를 맞춤

    1. 두 배열의 차원 수가 다르다면, 크기가 더 작은 차원이 다른 배열의 shape에 따라 원소가 반복하며 채워진다.
    2. 두 배열의 shape이 어떠한 차원에서도 같지 않다면, 1인 배열의 shape은 다른 배열의 shape과 같기 위해 늘어난다.
    3. 어떤 차원에서도 크기가 일치 하지 않고, 1이 아니면, 오류 뜬다

In [144]:
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [98]:
matrix + [100, 100, 100]
#(3, )의 벡터를 (1,3)크기로 맞춘 후 행을 따라 반복

matrix+[[100],
        [100],
        [100]]
#(3,1) 크기의 벡터가 열을 따라 반복

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

***   

## 1.7 최댓값, 최솟값 찾기

In [99]:
# 넘파이의 max, min 함수 사용
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

> ### max함수

In [101]:
np.max(matrix) #가장 큰 원소 반환

9

> ### min함수

In [102]:
np.min(matrix) #가장 작은 원소 반환

1

> >### axis 매개변수   
* axis 매개변수를 사용해 특정 축에 따라 연산을 수행 가능

In [110]:
np.max(matrix, axis=0) #열따라

array([7, 8, 9])

In [122]:
np.max(matrix, axis=1) #행따라

array([3, 6, 9])

> >### keepdims 매개변수
* 위 매개변수를 True로 지정하면 원본 배열의 차원과 동일한 결과 생성   
* 원본배열과 안전하게 브로드캐스팅 연산이 가능

In [134]:
vector_column2 = np.max(matrix, axis=1, keepdims=True)
#이전과 달리 (3,1)의 열벡터 생성
vector_column2

array([[3],
       [6],
       [9]])

In [135]:
vector_column = np.max(matrix, axis=1, keepdims=False)

matrix - vector_column

array([[-2, -4, -6],
       [ 1, -1, -3],
       [ 4,  2,  0]])

In [136]:
matrix - vector_column2

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [109]:
matrix #안전하게 브로드캐스팅 연산이 된것을 볼 수 있다.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

***   

## 1.8 평균, 분산, 표준편차 계산하기

> ### mean 함수   
평균반환

In [137]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

np.mean(matrix)

5.0

In [138]:
np.mean(matrix, axis=0) #각 열의 평균을 계산

array([4., 5., 6.])

> ### var함수
분산 반환

In [139]:
np.var(matrix)

6.666666666666667

> ### std함수
표준편차 반환

In [6]:
np.std(matrix)

2.581988897471611

> > ### ddof매개변수   
* 통계학에서 모집단의 샘플 자유도를 고려해 편향되지 않은 분산과 표준편차를 계산해야 한다   
* 훈련데이터의 독립적인 샘플 수 = 전체 샘플 수 -1   
* np.std와 np.var 함수에서 ddof매개변수를 1로 지정해 편향되지 않은 추정값을 얻을 수 있다.      

    1. ddof매개변수의 기본값은 0
    2. 판다스 데이터프레임의 std메서드는 ddof(data dgree of freedom) 기본값이 1

In [142]:
np.std(matrix, ddof=1)

2.7386127875258306

***   

## 1.9 배열 크기 바꾸기

In [144]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

matrix.reshape(2,6) #2x6행렬로 크기 변환

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

> ### reshape 함수
* 데이터 동일하게 유지하며 배열의 구조를 변경해 행과 열의 수를 다르게 조작할 수 있다   
* 주의!새로운 행렬은 원본과 원소 개수가 같아야 한다.(size사용해 원소 수 확인)
* 매개변수 -1은 가능한 많이라는 뜻 
  + reshape(1.-1)은 '행 하나에 열은 가능한 많이'의 의미이다.  

In [145]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

> * reshape에 정수 하나 입력 시 그 길이의 1차원 배열을 반환한다.

In [146]:
matrix.reshape(12) 
# matrix.reshape(-1)을 사용하면 길이 전체를 헤아릴 필요가 없다.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

> * ravel 메서드도 이와 동일한 작업 수행

In [123]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

***   

## 1.10 벡터나 행렬 전치하기

In [150]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### T메서드

각 원소의 행과 열의 인덱스를 바꾼다.


* 주의! 벡터는 단지 값의 모음이기 때문에 전치할 수 없음
   + 대괄호를 두번 사용하면 벡터 전치 가능
   + 일반적으로 벡터의 전치는 행 벡터를 열 벡터로 변환 또는 그 반대를 의미
   + numpy는 열 벡터 기준

In [147]:
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [148]:
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

> ### transpose 메서드
* T메서드 대신 사용가능


In [151]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

> * 튜플로 바꿀 차원을 직접 지정 가능

In [152]:
#2(0)x 3(1)x2(2)행렬 
matrix = np.array([[[1,2],
                  [3,4],
                  [5,6]],
                  
                 [[7,8],
                  [9,'A'],
                  ['B','C']]])

matrix.transpose((0, 2, 1))
#2(0)x 2(2)x3(1)행렬로 변환

array([[['1', '3', '5'],
        ['2', '4', '6']],

       [['7', '9', 'B'],
        ['8', 'A', 'C']]], dtype='<U11')

***

## 1.11 행렬 (1차원 배열로) 펼치기

In [156]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> ### flatten 메서드
* 행렬을 1차원 배열로 변환하는 간단한 메서드
* reshape 메서드와의 차이점 
    1. reshape은 넘파이 배열의 뷰를 반환 vs flatten은 새로운 배열 생성

In [157]:
vector_reshaped = matrix.reshape(-1)
vector_flattened = matrix.flatten()

#(0,0) 위치의 원소를 바꿔준다
matrix[0][0]= -1

vector_reshaped

array([-1,  2,  3,  4,  5,  6,  7,  8,  9])

In [158]:
matrix[0,1]=100

vector_reshaped

array([ -1, 100,   3,   4,   5,   6,   7,   8,   9])

In [159]:
vector_flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

>      2. 원본 배열에서 변경된 내용 반영 vs 배열을 복사해 새 배열을 생성하기 때문에 반영되지 않음

***

## 1.12 행렬의 랭크 구하기

In [20]:
import numpy as np
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])
# 첫번째 열과 두번째 열이 동일 -> 독립적인 열이 2개

np.linalg.matrix_rank(matrix) 

2

> ## matrix_rank 선행대수 메서드   
* 행렬의 랭크는 선형 독립적인 행 또는 열의 개수이다.   
* matrix_rank를 통해 행렬의 랭크를 쉽게 찾을 수 있다.   
* 특잇값 분해 방식으로 랭크를 계산
> > linalg() 모듈의 svd함수로 singular value decomposition을 구한 다음 0이 아닌 값 수를 헤아린다.

> ### np.linalg   
* 행렬 서브패키지

> ### svd(특이값 분해)
* 특이값으로 구성된 대각 행렬 S에서 0으로 이루어진 추가 행 또는 열을 제거
* u 표현식 A = U*S*V'에서 이러한 0과 곱해질 U 또는 V의 열도 제거
-    + 0과 열을 제거하면 분해의 정확도에 영향을 미치지 않으면서 실행 시간을 개선하고 필요한 저장 공간을 줄일 수 있다.

In [160]:
# svd 함수로 특잇값만 계산
s = np.linalg.svd(matrix, compute_uv=False)
#오차를 고려해 0에 가까운 아주 작은 값을 지정
np.sum(s > 1e-10)

3

In [161]:
np.linalg.svd(matrix, compute_uv=False)

array([100.52480472,  13.25008516,   0.44595859])

In [162]:
?np.sum

***

## 1.13 행렬식 계산하기

> ### 행렬식
* 정사각행렬이 나타내는 선형 변환이 부피를 확대시키는 정도를 나타냄
* 정방행렬에 의한 선형 변환의 특징을 나타내는 스칼라 값이다.
> > ##### 정방행렬
이란 nxn 행렬
* 정의 : n × n  정사각행렬의 집합을 Mat(n;K)로 쓰면, 행렬식은 다음 세조건을 만족시키는 유일한 함수 det: Mat(n;K) -> K 이다.
    1. 각 행에 대해 선형적이다.
    2. 두 행이 같은 행렬의 행렬식은 0이며, 행렬의 두 행을 교환하면 행렬식은 반수가 된다.
    3. 단위 행렬의 행렬식은 1이다.
* 예시
    1. 0X0 행렬 : det()=1
    2. 1X1 행렬 : det(a)=a
    3. 2X2 행렬 : det([[a,b],[c, d]]) = ad-bc
    4. 3x3 행렬 : det([[a,b,c],[d,e,f],[g,h,i]])= aei+bfg+cdh-ceg-bdi-afh   
     = a det([[e,f], [h,i]])-b det([d,f],[g.i])+c det([d,e],[g,h])

In [26]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

np.linalg.det(matrix)

0.0

> ## det 메소드
*행렬식 계산 메소드

***

## 1.14 행렬의 대각원소 추출하기

> ### diagonal메서드
* 대각원소 반환   
* 원본 배열의 뷰 반환, 반환된 배열의 원소를 바꾸려면 배열을 복사해 사용해야 함

In [27]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])


matrix.diagonal()

array([1, 4, 9])

> * 넘파이 diag함수도 대각원소를 추출   
1차원 배열이 주어졌을때 역으로 대각행렬 생성

In [31]:
#반환된 배열 변경을 위해선 복사
a=matrix.diagonal().copy()

a=np.diag(matrix)
print(a)

[1 4 9]


In [32]:
#1차원 배열이 주어지면 2차원 대각행렬 생성
np.diag(a)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

> * offset매개변수   
주 대각선에서 벗어난 대각원소를 얻을 수 있다

In [29]:
matrix.diagonal(offset=1)
# 주대각선 하나 위의 대각원소를 반환

array([2, 6])

In [30]:
matrix.diagonal(offset=-1)
# 주대각선 하나 아래의 대각원소를 반환

array([2, 8])

***

## 1.15 행렬의 대각합 계산하기

In [33]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

matrix.trace()

14

> ### trace 메서드
* **대각합을 반환한다**
* 행렬의 대각원소를 직접 더하는 ```
sum(matrix.diagonal())
```와 같다   
* offset 매개변수를 지원

In [34]:
#주 대각선 하나위의 대각원소의 합을 반환
matrix.trace(offset=1)

8

***
## 1.16 고윳값과 고유벡터 찾기

In [163]:
import numpy as np
matrix = np.array([[1,-1,3],
                  [1,1,6],
                  [3,8,9]])

#고유값, 고유벡터를 계산
eigenvalues, eigenvectors = np.linalg.eig(matrix)

eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [164]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

> ### 고유벡터  
: 스케일만 바뀌는 벡터(방향은 바뀌지 않음)   
* **Av=λv**(λ:고유값, v: 고유벡터)

> ### linalg.eig 함수
* 정방행렬의 고유값과 고유벡터를 계산
* 대칭행렬일 경우 더 빠르게 계산 가능
* 입력되는 값이 진짜 대칭행렬인지 검사하지 않는다

***
## 1.17점곱 계산하기 

In [40]:
import numpy as np

#두 벡터를 만든다
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

#점곱 계산
np.dot(vector_a, vector_b)

32

> 두 벡터 a와 b의 점곱 : (a1 x b1)+(a2 x b2)+...+(an x bn)
> ### dot함수
를 사용해 점곱 계산 가능
* @연산자로도 가능

> > #### @연산자
* 사실 np.dot이 아닌 np.matmul함수를 나타냄
* np.dot과 달리 스칼라 배열에 적용되지 않는다

In [41]:
scalar_a = np.array(1)
scalar_b = np.array(2)
np.dot(scalar_a, scalar_b)

2

In [43]:
#스칼라 배열 적용x
scalar_a @ scalar_b

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

***
## 1.18 행렬 덧셈 뺄셈

> ### add메서드
두 행렬 더함
> ### subtract메서드
두 행렬 뺌

* 간단하게 +와 - 연산자도 사용 가능

In [44]:
import numpy as np

matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [45]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [46]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

***
## 1.19 행렬 곱셈

In [48]:
import numpy as np
matrix_a = np.array([[1,1],
                    [1,2]])
matrix_b = np.array([[1,3],
                    [1,2]])

# 두 행렬을 곱함
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [49]:
matrix_a @ matrix_b 

array([[2, 5],
       [3, 7]])

In [50]:
#원소별 곱셈을 수행하려면 * 연산자 사용
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

> > np.dot함수
1. 다차원 배열에 적용 가능
2. 첫번째 배열의 마지막 차원과 두번째 배열의 끝에서 두번째 차원이 동일해야 함   
    * (a,b,c,D)크기의 배열과 (e,f,D,h)크기의 배열이 있을 때   두 배열의 점곱 결과는 (a,b,c,e,f,h) 크기의 배열

> > np.matmul 함수와 @연산자
1. 다차원 배열을 마지막 두 차원이 단순히 쌓인 것으로 취급
    * (a,b,c,D)크기의 배열과 (e,f,D,h)크기의 배열이 있을 때 a와 e가 같거나 둘 중 하나는 1이어야 함,   
    또한 b와 f가 같거나 둘 중 하나가 1이어야 함
    * 연산의 결과 (a', b', c, h) 크기의 배열을 만든다.  
    (a'는 a와 e 중 1이 아닌 값,   
    b'는 b와 f 중 1이 아닌 값)

In [171]:
a = np.random.rand(2,1,4,5)
b = np.random.rand(1,3,5,6) 

np.dot(a,b).shape

(2, 1, 4, 1, 3, 6)

In [172]:
a

array([[[[0.53657921, 0.89667129, 0.99033895, 0.21689698, 0.6630782 ],
         [0.26332238, 0.020651  , 0.75837865, 0.32001715, 0.38346389],
         [0.58831711, 0.83104846, 0.62898184, 0.87265066, 0.27354203],
         [0.79804683, 0.18563594, 0.95279166, 0.68748828, 0.21550768]]],


       [[[0.94737059, 0.73085581, 0.25394164, 0.21331198, 0.51820071],
         [0.02566272, 0.20747008, 0.42468547, 0.37416998, 0.46357542],
         [0.27762871, 0.58678435, 0.86385561, 0.11753186, 0.51737911],
         [0.13206811, 0.71685968, 0.3960597 , 0.56542131, 0.18327984]]]])

In [173]:
b

array([[[[0.14484776, 0.48805628, 0.35561274, 0.94043195, 0.76532525,
          0.74866362],
         [0.90371974, 0.08342244, 0.55219247, 0.58447607, 0.96193638,
          0.29214753],
         [0.24082878, 0.10029394, 0.01642963, 0.92952932, 0.66991655,
          0.78515291],
         [0.28173011, 0.58641017, 0.06395527, 0.4856276 , 0.97749514,
          0.87650525],
         [0.33815895, 0.96157015, 0.23170163, 0.94931882, 0.9413777 ,
          0.79920259]],

        [[0.63044794, 0.87428797, 0.29302028, 0.84894356, 0.61787669,
          0.01323686],
         [0.34723352, 0.14814086, 0.98182939, 0.47837031, 0.49739137,
          0.63947252],
         [0.36858461, 0.13690027, 0.82211773, 0.18984791, 0.51131898,
          0.22431703],
         [0.09784448, 0.86219152, 0.97291949, 0.96083466, 0.9065555 ,
          0.77404733],
         [0.33314515, 0.08110139, 0.40724117, 0.23223414, 0.13248763,
          0.05342718]],

        [[0.72559436, 0.01142746, 0.77058075, 0.14694665, 0.079522

In [56]:
np.matmul(a,b).shape

(2, 3, 4, 6)

***
## 1.20 역행렬

> 정방행렬 A의 역행렬을 A'라 하면   
**AA'= I**(I는 단위 행렬)   
이 성립된다.

In [176]:
import numpy as np
matrix = np.array([[1, 4],
                  [2, 5]])

#역행렬을 계산한다
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

> ###linalg.inv 함수
* 역행렬 A'를 계산한다

In [177]:
# 행렬과 역행렬을 곱해 단위행렬을 확인한다
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

> ### pinv함수
* 정방행렬이 아닌 행렬의 역행렬을 계산 = ***유사 역행렬***

In [180]:
matrix = np.array([[1,4,7],
                  [2,5,8]])

np.linalg.pinv(matrix)`

array([[-1.16666667,  1.        ],
       [-0.33333333,  0.33333333],
       [ 0.5       , -0.33333333]])

In [181]:
matrix @ np.linalg.pinv(matrix)

array([[1.00000000e+00, 2.22044605e-15],
       [1.77635684e-15, 1.00000000e+00]])

***
## 1.21 난수 생성하기

넘파이의 ***random 모듈*** 사용
> 1. 실수 난수 생성 → **random 함수**사용

In [76]:
import numpy as np
np.random.seed(0) #초깃값 지정 -> 위험

#0.0과 1.0 사이 3개의 실수 난수 생성
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

> 2. 정수 난수 생성 → **randint 함수** 사용

In [182]:
#0과 10 사이 3개의 정수난수 생성
np.random.randint(0, 11, (3,3))

array([[7, 5, 5],
       [8, 0, 8],
       [3, 6, 9]])

> 3. 분포 설정해 그 속에서 난수 생성하기

In [78]:
# 1) 평균이 0.0이고 표준편차가 1.0인 정규분포에서 3개의 난수 생성
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [79]:
# 2) 평균이 0.0이고 스케일이 1.0인 로지스틱 분포에서 3개 난수 생성
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [80]:
# 3)1.0보다 크거나 같고 2.0보다 작은 3개의 난수 생성
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

* 동일한 seed을 지닌 난수 생성은 항상 같은 결과를 출력한다.

> #### 1. random 함수, sample 함수   
= random_sample 함수   
= uniform 함수(최솟값 0.0 최댓값 1.0으로 지정) 

In [84]:
np.random.random_sample((2,3))
#np.random.random((2,3)), np.random.sample((2,3))과 동일 
#np.random.uniform(0.0, 1.0, (2, 3))과 동일 

array([[0.53737323, 0.75861562, 0.10590761],
       [0.47360042, 0.18633234, 0.73691818]])

> #### 2.rand함수
* 크기를 튜플이 아니라 개별적인 매개변수로 전달

In [83]:
np.random.rand(2,3)
#np.random.random_sample((2,3))과 동일

array([[0.47360805, 0.80091075, 0.52047748],
       [0.67887953, 0.72063265, 0.58201979]])

> #### 3.randint함수
* 최솟값을 포함하고 최댓값은 포함하지 않은 정수 난수 생성

In [85]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> #### 4. standard_normal함수
* 평균이 0.0이고 표준편차가 1.0인 정규분포의 난수 생성
* normal함수와 동일
> > 4.1 rand 함수
 * 위 함수와 동일하나, 크기를 튜플이 아닌 개별적인 매개변수로 전달

In [89]:
np.random.standard_normal((2,3))

array([[-0.38093141,  0.11495917,  0.34531264],
       [-1.73495876,  1.65835111,  2.29977152]])

In [90]:
np.random.randn(2,3)

array([[-0.47113526,  1.26271548, -1.17051545],
       [ 1.0657892 , -0.69993739,  0.14407911]])

> #### 5. choice 함수
* 배열의 원소 중 랜덤하게 지정된 횟수만큼 샘플 생성
* 또는 0~(정수-1) 사이의 원소 중 랜덤하게 샘플 선택

In [91]:
np.random.choice([0,1,2], 5)
# .choice(3,5)와 동일
#0~2 사이 정수 중 랜덤하게 5번 뽑음

array([2, 0, 1, 2, 0])

> #### 6. shuffle 함수
* 입력된 배열을 섞는다

In [92]:
a = np.array([0,1,2,3,4])
np.random.shuffle(a)
a

array([3, 4, 1, 0, 2])

#### 7.permutation 함수

* 입력된 배열의 복사본을 만들어 섞은 후 반환
* 정수를 입력하면 0에서부터 (정수-1)까지 숫자를 섞은 후 반환

In [94]:
np.random.permutation(a)
#a는 변경되지 않음

array([2, 1, 3, 0, 4])

In [95]:
np.random.permutation(5)

array([0, 1, 4, 3, 2])